### ISSUE TITLE
Please release company-irony-c-headers on MELPA stable

### ISSUE THREAD

**Issue by ghost** [hotpxl/company-irony-c-headers#11]
company-irony-c-headers hasn't seen a release on [MELPA stable](https://stable.melpa.org/) yet. Please consider releasing company-irony-c-headers on MELPA stable.

**Comment by hotpxl** [comment]
Sorry I missed your issue somehow. I'll look into that.

**Comment by hotpxl** [comment]
Now it's on melpa stable.

**Comment by ghost** [comment]
thanks!
