### ISSUE TITLE
Add extra include paths/work together with company-c-headers?

### ISSUE THREAD

**Issue by sonictk** [hotpxl/company-irony-c-headers#12]
Hi:

I was trying to find a way to add additional include paths to company-irony-c-headers through a .dir-locals.el file or getting it to work with company-c-headers existing include flags.

Is it possible to pass in additional include paths to company-irony-c-headers for this purpose in a .dir-locals.el file or combine the two completions output from company-c-headers and company-irony-c-headers?

I have not been able to find a way to add header files using a .dir-locals file. Right now I do this in one of my emacs startup files:

```
; C++ Autocomplete for clang
(require 'fuzzy)
(require 'auto-complete-clang)
(require 'auto-complete)
(define-key c++-mode-map (kbd "C-S-SPC") 'ac-complete-clang)

; Use irony autocomplete for C languages
(add-hook 'c++-mode-hook 'irony-mode)
(add-hook 'c-mode-hook 'irony-mode)
(add-hook 'objc-mode-hook 'irony-mode)

;; replace the `completion-at-point' and `complete-symbol' bindings in
;; irony-mode's buffers by irony-mode's function
(defun my-irony-mode-hook ()
  (define-key irony-mode-map [remap completion-at-point]
    'irony-completion-at-point-async)
  (define-key irony-mode-map [remap complete-symbol]
    'irony-completion-at-point-async))
(add-hook 'irony-mode-hook 'my-irony-mode-hook)
(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)
(setq w32-pipe-read-delay 0)

; Use company-mode with irony
(add-hook 'irony-mode-hook 'company-irony-setup-begin-commands)
(setq company-backends (delete 'company-semantic company-backends))
; Enable completion of C/C++ headers
;; Load with `irony-mode` as a grouped backend
(require 'company-irony-c-headers)
(require 'company-c-headers)
(eval-after-load 'company
  '(add-to-list
    'company-backends '(company-irony-c-headers company-irony company-c-headers)))

; (add-to-list 'company-backends 'company-c-headers)
; Set autocomplete header search paths based on OS type
; NOTE: Can find the include paths with the shell command ``echo "" | g++ -v -x c++ -E -``
(cond
 ((string-equal system-type "windows-nt") ; any flavor of Windows
    (setq ac-clang-flags
          (mapcar (lambda (item)(concat "-I" item))
                  (split-string
    "
    c:/Qt/4.8.5/include
    "
    )))
    (add-to-list 'company-c-headers-path-system "c:/Qt/4.8.5/include")
  )
((string-equal system-type "gnu/linux")
 )
((string-equal system-type "darwin") ; Mac
)
)

; Use tab-completion with no delay
(setq company-idle-delay 0.5)
(define-key c-mode-map [(control tab)] 'company-complete)
(define-key c++-mode-map [(control tab)] 'company-complete)
```

But when I hit C-tab, I only get the completions coming from company-irony-c-headers (i.e.stdlib stuff like string, vector), and not company-c-headers (i.e. QtCore, QtGui). Is there a way I can combine both backend completion results so that company-complete shows them all? If I run company-c-headers manually, the completions show up, so I know at least the candidates themselves are being loaded, they're just not being combined with the candidates in company-complete for some reason.

Additionally, I was trying to set the include paths for company-c-headers using a .dir-locals.el file instead of hardcoding it in my emacs startup script, like so:

```
((c++-mode (eval setq company-clang-arguments (append 
                                               company-clang-arguments
                                               '("-I C:/Qt/4.8.5/include")))))
```

But this doesn't seem to have any effect whatsoever when I attempt to use company-c-headers; it doesn't show me the completions from Qt.

**Comment by hotpxl** [comment]
company-irony-c-headers is meant to be a extension of irony. So it parses settings from irony. In irony mode, I would usally have a `.clang-complete` file with all my compilation flags (like `-I extra input directories`). If you add those directories like this, company-irony-c-headers will pick them up.

Under the hood, company-irony-c-headers takes the same flags and pass it into clang. Clang will figure out what directories to search for.

Does this answer your question?

**Comment by sonictk** [comment]
@hotpxl Could you post a sample `.clang_complete` file? I can't seem to get mine working properly; the paths don't seem to be added to the directories that irony picks up.

**Comment by hotpxl** [comment]
```
-std=c++14
-Wall
-Wextra
-pthread
-Iinclude
-Ibuild
-Ithird_party/include
```

This is a sample `.clang_complete` I use for one of my project.

There are some functions you could play with to help debugging. `company-irony-c-headers--search-paths` prints all search paths it gets from the compiler. So if you added something but it didn't show up here, there might be a problem in the compiler on irony.

**Comment by sonictk** [comment]
I finally figured it out, I was trying to add my Qt header files with:

`-IthirdParty/Qt/4.8.5/include`

Instead of doing:

`-IthirdParty/Qt/4.8.5/include/**` 

in order to recursively find the header files in subdirectories. Auto-completion for headers is working now!

Thanks for the assistance!

**Comment by hotpxl** [comment]
You are welcome!

**Comment by sonictk** [comment]
Unfortunately I have re-opened this issue because adding `/**` to the directories is causing `company-irony` to fail completions. However, if I just use the following `.clang_complete` file:

```
-std=c++14
-Wall
-Wextra
-pthread
-Iinclude
-Ic:/Qt/4.8.5/include
```

When I try to get completions in my headers, irony-server crashes with the following message:

```
Company: An error occurred in auto-begin
Company: backend (company-irony-c-headers company-irony) async timeout with args (candidates Qt)
irony process stopped!
```

Is there something else that I've missed here for setting up company-irony-c-headers?

**Comment by hotpxl** [comment]
I've never encountered a timeout before. It may because there are too many header files and the search is too slow. But I doubt that. It may also because Irony is somehow timing out.

You can try the interactive command `company-irony-c-headers` using <kbd>M-x</kbd> at the point of completion and try two tools out separately.

As far as for the setup, I think everything is just fine. I don't process the file directly. Clang produces a nicely normalized search paths.

**Comment by sonictk** [comment]
@hotpxl So it seems that that was it, irony itself is timing out. If I call `company-irony-c-headers` it completes almost instantly, but combining the backends seems to cause timeouts.

Is there a way to increase the timeout limit for irony? I couldn't find one just searching around the options in `customize-group`.

EDIT: Never mind, found the variable `company-async-timeout` which seems to work for this case. Thanks again for the help!
