### ISSUE TITLE
Why do I need this next to company-irony?

### ISSUE THREAD

**Issue by Martinsos** [hotpxl/company-irony-c-headers#14]
Could you please explain in README why I need this package next to company-irony?

**Comment by hotpxl** [comment]
Last time I checked, company-irony does not auto-complete include headers. Are they doing this right now?

**Comment by Martinsos** [comment]
Aha! Well I just started using company-irony so I did not get to it yet, but noticed company-irony-c-headers being mentioned and could not figure out was it is useful for. Thanks for response!

**Comment by hotpxl** [comment]
Great. I'll put on the readme
