### ISSUE TITLE
Autocomplete keeps first #

### ISSUE THREAD

**Issue by jstaursky** [hotpxl/company-irony-c-headers#15]
For some reason auto-completing headers is not replacing the initial #  but adding another one as apart of the autocomplete.

For example typing "#in" and accepting any of the autocomplete suggestions results in "##include <>"

how do I fix this?

**Comment by hotpxl** [comment]
I'm not sure what your setup is like. If you enter `#in` and it gives you options, most likely it is from some other plugin. company-irony-c-headers is triggered when you have at least entered `#include <` or `#include "`

If you use company-mode. It will show the current completion engine in the status bar (minor modes).

**Comment by jstaursky** [comment]
hmmm, I guess it might be irony then, but then I don't understand why it only happens on headers. Anyway I'll probably end up writing an advising function or something. Thanks for the tip.
