### ISSUE TITLE
How to use custom include path as libraries path?

### ISSUE THREAD

**Issue by stardiviner** [hotpxl/company-irony-c-headers#16]
I wan to use `company-irong-c-headers` for Arduino libraries in `~/Arduino/libraries/`
Here is the structures:
`~/Arduino/libraries/<sketch>/src/{*.cpp, *.h}`

**Comment by hotpxl** [comment]
This library uses settings from [irony-mode](https://github.com/Sarcasm/irony-mode) to set up search paths. I use irony-mode, so I would have a `.clang_complete` file that specifies all my compiler flags, including `-Iinclude_paths`. Then irony-mode would work and this would work as well.

**Comment by stardiviner** [comment]
After check out many articles about `irony-mode` and C Build/Make Systems. Still don't understand how to specify include path for Arduino.
If I want to only include libraries under `~/Arduino/libraries/<sketch>/src/{*.cpp, *.h}`. What should I do?

**Comment by stardiviner** [comment]
After checked out:
- [x] https://sarcasm.github.io/notes/dev/compilation-database.html#clang
- [x] https://github.com/Sarcasm/irony-mode/wiki/Arduino
- [x] https://github.com/Sarcasm/irony-mode/issues/201

I created `.clang_complete` file under `~/Arduino/`
Its content is:
```
-I/home/stardiviner/Arduino/libraries/
```
But `company-irony-c-headers` still doesn't work.

**Comment by hotpxl** [comment]
That sounds strange. If you specify `-I/home/stardiviner/Arduino/libraries/`, it would search for `.h` files under that directly. I wonder if the header files are under a `include` directory.

**Comment by stardiviner** [comment]
No, they are not under `include/` directory.
Here is the structure in `~/Arduino/libraries/` (The `src/` directory should be searching):
```
└── WiFi_Link
    ├── changelog.md
    ├── examples
    │   ├── CheckWiFiLinkFirmwareVersion
    │   │   └── CheckWiFiLinkFirmwareVersion.ino
    │   ├── ConnectNoEncryption
    │   │   └── ConnectNoEncryption.ino
    │   ├── ConnectWithWEP
    │   │   └── ConnectWithWEP.ino
    │   ├── ConnectWithWPA
    │   │   └── ConnectWithWPA.ino
    │   ├── ScanNetworks
    │   │   └── ScanNetworks.ino
    │   ├── SimpleWebServerWiFi
    │   │   └── SimpleWebServerWiFi.ino
    │   ├── Tools
    │   │   └── EspRecovery
    │   │       └── EspRecovery.ino
    │   ├── WiFiChatServer
    │   │   └── WiFiChatServer.ino
    │   ├── WifiRestServer
    │   │   └── WifiRestServer.ino
    │   ├── WiFiUdpNtpClient
    │   │   └── WiFiUdpNtpClient.ino
    │   ├── WiFiUdpSendReceiveString
    │   │   └── WiFiUdpSendReceiveString.ino
    │   ├── WiFiWebClient
    │   │   └── WiFiWebClient.ino
    │   ├── WiFiWebClientRepeating
    │   │   └── WiFiWebClientRepeating.ino
    │   └── WiFiWebServer
    │       └── WiFiWebServer.ino
    ├── keywords.txt
    ├── library.properties
    ├── README.adoc
    └── src
        ├── utility
        │   ├── comm.cpp
        │   ├── comm.h
        │   ├── debug.h
        │   ├── server_drv.cpp
        │   ├── server_drv.h
        │   ├── spi
        │   │   ├── spi_drv.cpp
        │   │   └── spi_drv.h
        │   ├── uart
        │   │   ├── SC16IS750.cpp
        │   │   ├── SC16IS750.h
        │   │   ├── serial.cpp
        │   │   ├── serial.h
        │   │   ├── uart_drv.cpp
        │   │   └── uart_drv.h
        │   ├── wifi_drv.cpp
        │   ├── wifi_drv.h
        │   ├── wifi_spi.h
        │   ├── wl_definitions.h
        │   └── wl_types.h
        ├── WiFiClient.cpp
        ├── WiFiClient.h
        ├── WiFiLink.cpp
        ├── WiFiLink.h
        ├── WiFiServer.cpp
        ├── WiFiServer.h
        ├── WiFiUdp.cpp
        └── WiFiUdp.h
```

**Comment by stardiviner** [comment]
And I tried `-I/home/stardiviner/Arduino/libraries/` in file `~/Arduino/.clang_complete` again.
It can complete with `#include <WiFi/src/WiFi.h>`. But not directory `#include <WiFi.h>`. With relative path, Arduino will report error.

**Comment by hotpxl** [comment]
I think the problem here is that you have `-I/home/stardiviner/Arduino/libraries/` in the compilation file. Then the compiler will search for files relative to this path. If you want to include `/home/stardiviner/Arduino/libraries/WiFi_Link/src/WiFiLink.h`, you have to type in `#include <WiFi_Link/src/WiFiLink.h>` in your source file. Or otherwise the compiler will report error just as you have described. If you want to be able to `#include <WiFiLink.h>`, you need to add the whole `/home/stardiviner/Arduino/libraries/WiFi_Link/src/` to your include search paths. Clang and G++ will not recursively search include paths, nor do they understand your project organization.

A good rule of thumb is, if you provide the flags to the compiler and it fails to compile, it means that the error lies with the compilation flags you are using.

**Comment by stardiviner** [comment]
I see. Thanks
