### ISSUE TITLE
Should auto-trigger completion on directories

### ISSUE THREAD

**Issue by Sarcasm** [hotpxl/company-irony-c-headers#3]
Hello,

After a simple test it seems to work nicely.

I noticed one thing. Company triggers the completion after `company-minimum-prefix-length` (3 characters by default). It would be nice to to trigger the completion automatically after a '/' though.

So if I ask for:

``` cpp
#include <boost/[]>
```

Completion should be triggered automatically.

This is achievable via company's `prefix` return value, see https://github.com/company-mode/company-mode/blob/c6af7d29ef7b8d2b6b4800151511ead26c521532/company.el#L346-L347

**Comment by hotpxl** [comment]
Thanks for the comment. There is a corner case however. For example I have "a/b/c.h" to complete. I type "a/", the completion engine shows me "a/b/". I hit tab to complete "a/b/", then the completion prompt disappears and won't show "a/b/c.h" as a candidate. I am pretty sure this is how `company` works, it just won't trigger a `prefix` command again.

**Comment by Sarcasm** [comment]
indeed, I have a hack for this in company-irony, see https://github.com/Sarcasm/company-irony/blob/29becb8824cacb1ea6f8c823d06ba65512c62e3d/company-irony.el#L85-L105

I'm not sure if it is a good idea to use it here too or not. At least it may be worth trying. In the end, I hope to see your work being included directly in company-irony, meaning we would have the hack only once.

**Comment by hotpxl** [comment]
Looks not so intuitive.I guess I'll go with the manual way. LOL
