### ISSUE TITLE
post-completion shouldn't insert the end character if already present

### ISSUE THREAD

**Issue by Sarcasm** [hotpxl/company-irony-c-headers#4]
The post-completion action add a quote `"` or tag `>` even if already present, producing things like this after expansion:

``` cpp
#include <ios[]>

#include <iostream>[]>
```

`[]` represents the cursor

**Comment by hotpxl** [comment]
Thanks for the comment!

**Comment by Sarcasm** [comment]
No problem, another thing you could do, is still to move the cursor after the quote/tag when it is already present.

**Comment by hotpxl** [comment]
Good idea! Fixed.
