### ISSUE TITLE
Incorrect working directory on reload compiler output

### ISSUE THREAD

**Issue by harveyt** [hotpxl/company-irony-c-headers#7]
The company-irony-c-headers--working-dir is used to set default-directory, that must end in slash to work correctly (otherwise it ends up in parent directory). This confuses the reload of compiler output.

Fixed as follows:

```
 (defun company-irony-c-headers--working-dir ()
    "Get working directory."
    (if irony--working-directory
        (concat irony--working-directory "/")
      default-directory))

```

**Comment by hotpxl** [comment]
Strangely I'm getting directory with slash appended properly on my computer. I can go ahead and add a layer of `file-name-as-directory` so it will append slash if not exist. But I wonder if it's breaking other stuff in irony.
