### ISSUE TITLE
Dosen't completes system headers

### ISSUE THREAD

**Issue by agauniyal** [hotpxl/company-irony-c-headers#8]
Is able to show completion for projects based header files (`#include "someheader.h"`) but fails to show anything on `#include <` .

**Comment by hotpxl** [comment]
Interesting. Could you <kbd>Meta</kbd> + <kbd>:</kbd> and run `(company-irony-c-headers-reload-compiler-output)` to reload compiler options. If this does not fix, could you <kbd>Meta</kbd> + <kbd>:</kbd> and run `(company-irony-c-headers--search-paths)` and post the result here?

**Comment by agauniyal** [comment]
I ran `company-irony-c-headers-reload-compiler-output` & waited for a sec or 2 and it started completing headers. Well maybe it was already completing but I have to wait for atleast 2 seconds to let it show completion. ie. type `#include <io` ... wait for approx 2 secs & then it shows those completion.

**Comment by hotpxl** [comment]
This could happen for the first time, because it needs to wait for the compiler to parse command line options and calculate a set of include paths.

**Comment by agauniyal** [comment]
Yup and I'm satisfied :+1: Thanks.

**Comment by silgon** [comment]
Same problem here, but when I type `company-irony-c-headers-reload-compiler-output`, this message appears `apply: Searching for program: no such file or directory, clang++`. So I'm not able to see the headers. Can I have some help?

**Comment by hotpxl** [comment]
@silgon Probably you have a different executable for `clang++`. You can set `company-irony-c-headers--compiler-executable` to the one you have.

**Comment by silgon** [comment]
Thanks. I had `clang-3.5` installed which had not the clang++ command. Sorry, my bad.
