### ISSUE TITLE
Adding user path in addition to system paths

### ISSUE THREAD

**Issue by jwintz** [hotpxl/company-irony-c-headers#9]
Hello,

Is it possible as in `company-c-headers` to add user directories for the completion ?

```
(add-to-list 'company-irony-c-headers-user-path '"/home/...")
(add-to-list 'company-irony-c-headers-user-path '"/home/...")
(add-to-list 'company-irony-c-headers-user-path '"/home/...")
```

Thanks !

**Comment by hotpxl** [comment]
You are supposed to this in Irony. I would place a `.clang_complete` file in the root dir of the project and add `-Ipath0`, `-Ipath1` and so on. You could also share info with Irony in this way.

**Comment by jwintz** [comment]
You are right. I figured this out by using compilation databases for irony using a cmake based project, and got my c headers completion directly. This means company-irony-headers works out the box.

My question however remains. I have filled an issue to irony-mode to ask for user search path specified directly when configuring irony-mode in emas-lisp.

Thanks !

**Comment by hotpxl** [comment]
If you are using cmake and `INCLUDE_DIRECTORIES`, it should already be in the compilation database. I'm not sure if it's working properly since i've only used the `.clang_complete` way.
